wis2node/data/observations.py
Update based on https://github.com/wmo-im/csv2bufr/pull/14
=> update date handling of csv2bufr objects

Dockerfile, requirements.txt, wis2node/metadata/discovery.py
- Dockerfile updates:
- streamline install packages from GitHub sources for development
- cleanups (50% reduction in size of resulting image)
- fix f-string formatting in code
=> dockerfile updates

Dockerfile, docker/data-consumer/Dockerfile, docker/data-consumer/config/default.conf, docker/docker-compose.yml, docker/wis2box/config/default.conf
=> implemented logStdout so docker logs works idiomatically

docs/source/development.rst, docs/source/extending-wis2box.rst, wis2box/api/__init__.py, wis2box/api/backend/elastic.py, wis2box/data/observations.py
- derive filename from data transform given https://github.com/wmo-im/csv2bufr/commit/235a5b561f3df9b13681b91a644f5b5cfa941f8d
- docs updates
- ensure `--topic-hierarchy` is passed for API workflow
=> update docs, derive filename from data transform, safeguard API workflows

wis2box-ctl.py
Added --simulate that prints what it is doing.
Wanted to see the resultant docker-compose etc... commands... wanted a simulate mode.
saw the argument parsing was fairly primitive. fixed it.
=> converted command line parsing to use argparse library.

wis2box-ctl.py
* "./wis2box-ctl.py login data-consumer"  now works... can supply alternatives to (default) wis2box container.
* in commands where it makes sense, can supply containers as arguments
to shutdown, query or start up individual containers.
* up & down now allowed as synonyms for start & stop.
=> Wis2box goodies

.github/workflows/docs.yml, docs/source/data-access/R.ipynb, docs/source/installation.rst, requirements-dev.txt
Fix docs CI and various small additions to docs to trigger builds.
=> [WIP] Docs CI

.github/workflows/docs.yml
Checkout branch of main before publishing
=> fix docs CI workflow

examples/python-mqp-subscribe.py
adding topic display to python-mqp-subscription example.
=> one liner to do what the branch says.

.github/workflows/tests-docker.yml, docs/source/quickstart.rst, requirements-dev.txt, tests/integration/test_workflow.py, wis2box/api/__init__.py
Adds integration tests and minor doc update.
=> add integration tests

docs/source/services.rst, wis2box/metadata/discovery.py
- add OGC API example URLs
- rename services to align with WIS 2.0 architecture
- fix binding to discovery metadata temporal query property
=> Doc updates 2022 03 06

.github/workflows/tests-docker.yml, docs/source/extending-wis2box.rst, wis2box/data/observations.py
Aligns with https://github.com/wmo-im/csv2bufr/pull/64
=> rename default observation processing

Dockerfile, wis2box/data/base.py
=> do not yield files that error out

.github/workflows/tests-docker.yml, Dockerfile, tests/integration/test_workflow.py, wis2box/data/base.py, wis2box/data/bufr4.py, wis2box/handler.py, wis2box/topic_hierarchy.py
- [Use event driven workflow for CI](https://github.com/wmo-im/wis2box/commit/fcfc602c551f6625c60965af210b340517caf273)
- remove duplicated line in Dockerfile
- Update integration tests for new geojson format
- [fix flake8](https://github.com/wmo-im/wis2box/commit/b0f3d13468d686e32c933e03d59390f85d556ddf)
=> Pass GitHub tests

docker/wis2box/wis2box.cron, docs/source/running/data-retention.rst, wis2box/data/__init__.py, wis2box/env.py, wis2box/util.py
- docker/wis2box/wis2box.cron: Update cron job to run daily. Add archive cron.
- docs/source/running/data-retention.rst: Update documentation to show non-default behavior
- wis2box/data/__init__.py: Update archive function to only move files, creating directories as needed. Make `wis2box data clean --days=3` cast days arg as int.
- wis2box/env.py: Make archive directory on env creation.
- wis2box/util.py: Update walk_path docstring.
=> Amend clean and archive cron jobs

wis2box/metadata/station.py
=> delete stations before publish/re-publish

wis2box/metadata/discovery.py, wis2box/util.py
=> remove embedded auth from MQP URL

tests/integration/test_workflow.py, wis2box/metadata/station.py
Smaller version of https://github.com/wmo-im/wis2box/pull/235 just addressing the station topic.
=> Add topic as station queryable

wis2box/api/config/pygeoapi.py
Include retry strategy in to pygeoapi configuration API session for unexpected responses. wis2box sometimes fails on startup because wis2box-api is not yet running.
=> Add retry strategy to pygeoapi config api

docker/wis2box-auth/Dockerfile
pull wis2box image from github
=> fix wis2box-auth

.github/workflows/tests-docker.yml, docker/entrypoint.sh, docs/source/quickstart.rst, docs/source/running/api-publishing.rst, wis2box/__init__.py, wis2box/api/__init__.py, wis2box/api/backend/base.py, wis2box/api/backend/elastic.py, wis2box/api/config/pygeoapi.py, wis2box/data/__init__.py, wis2box/data/base.py, wis2box/data/geojson.py, wis2box/handler.py, wis2box/metadata/discovery.py, wis2box/metadata/station.py, wis2box/pubsub/message.py, wis2box/pubsub/subscribe.py
- Re-implements `wis2box.api` module as entrypoint for modifying configuration and backend. 
- Moves `wis2box api setup` to wrap the messages collection setup into the subscriber. 
- Renames generate_collection_metadata functions to gcm.
=> Facilitate api backend and configuration actions through wis2box.api

wis2box-ctl.py
based on the thread in Slack, ensure start/stop uses docker-compose commands and surpress loki error message
=> fixes for docker-compose

docker/default.env, docs/source/configuration.rst
Implements #261, in conjunction with https://github.com/wmo-im/wis2box-ui/pull/54
=> make basemaps configurable (#261)

config_examples/data-mappings.yml.example-synop-bufr, config_examples/data-mappings.yml.example-synop-csv, docs/source/running/data-pipeline-plugins.rst, tests/integration/test_workflow.py, wis2box/data/bufr2geojson.py, wis2box/data/bufr4.py, wis2box/data/csv2bufr.py, wis2box/resources/data-mappings.yml
- Post geojson directly to api in bufr2geojson.
- Split bufr4.py into bufr4.py and bufr2geojson.py
- Rename observations.py to csv2bufr.py
=> Update data module file names

wis2box/data/base.py, wis2box/pubsub/message.py
=> add data-id to notification message (#268)

docs/source/data-access/r-api.ipynb, docs/source/extending-wis2box.rst, tests/integration/test_workflow.py, wis2box/data/bufr4.py, wis2box/metadata/station.py
In support of https://github.com/wmo-im/wis2box/issues/280
=> normalize on normalize on wigos_station_identifier (#280)

Dockerfile, tests/integration/test_workflow.py, wis2box/data/base.py, wis2box/pubsub/message.py
=> add wigos_station_identifier to data notifications

Dockerfile, docker/entrypoint.sh, docker/wis2box/wis2box.cron
=> add username to cron.d (#240)

docker/docker-compose.yml
=> add memory limits for default ES setup

docker/watchpuppy/watchpuppy.py, wis2box/api/backend/elastic.py, wis2box/pubsub/message.py
fix to align to WIS2 notification message (`s/pubTime/pubtime/g`)
=> Pubsub message update

docker/mqtt_metrics_collector/mqtt_metrics_collector.py, wis2box/pubsub/mqtt.py
enable_tls ensure mqtts works correctly and to ensure mqtt_metrics_collector monitors WIS2BOX_BROKER_PUBLIC correctly 
Tested with new external broker at mqtts://demo.wis2box.wmo.int !
=> mqtts fixes

docker/docker-compose.monitoring.yml, docker/grafana/dashboards/cadvisor.json, docker/loki/loki-config.yml, docker/prometheus/prometheus.yml
add additional services to loki monitoring
add loki config to enable retention period
add cadvisor service and add prometheus config to scrap cadvisor
add cadvisor dashboard to grafana
=> Monitoring

wis2box/pubsub/message.py
Adds link object to data notifications when source is a station/has a WSI.
=> add WSI as link relation to data notifications

Dockerfile, docker/docker-compose.subscribe-download.yml, docker/wis2box-subscribe-download/Dockerfile, docker/wis2box-subscribe-download/local.yml, docs/source/data-access/index.rst, docs/source/data-access/pywis-pubsub.rst, docs/source/index.rst, requirements.txt
=> add pywis-pubsub PubSub utility

Dockerfile
- Install pygeos for geos/shapely2.0 support
=> Pin shapely in Dockerfile

docker/docker-compose.yml, docker/elasticsearch/elasticsearch.yml, docs/source/running/tldr.rst, examples/config/surface-weather-observations.yml, examples/config/synop-bufr-mappings.yml, examples/config/synop-csv-mappings.yml, examples/config/wis2box.extended.dev
lowercase the upper-case example
attempt to remove elasticsearch warning by adding elasticsearch-configuration-file
=> Bugfix 0.5

Dockerfile
=> bump bufr2geojson dependency (#331)

wis2box/data/base.py, wis2box/data/csv2bufr.py
Updates aligning with https://github.com/wmo-im/csv2bufr/pull/83
=> update to latest csv2bufr changes

examples/config/station_list.csv
=> update example station list (#358)

docs/source/community/troubleshooting.rst, docs/source/reference/running/station-metadata.rst, docs/source/user/setup.rst
update documentation for station_list.csv
=> update documentation for station_list.csv

wis2box-management/wis2box/api/__init__.py, wis2box-management/wis2box/api/backend/elastic.py, wis2box-management/wis2box/metadata/station.py
=> flush station API backend before re-publishing (#371)

docs/source/reference/running/data-pipeline-plugins.rst, wis2box-management/wis2box/metadata/discovery.py
=> add bufr4 plugin description (#313)

wis2box-subscribe-download/local.yml
Aligns with https://github.com/wmo-im/pywis-pubsub/pull/18
=> update wis2box-subscribe-download config based on latest pywis-pubsub updates

wis2box-management/Dockerfile
use eccodes-base-image
Addresses #314 #328
=> use eccodes-base-image

docs/source/reference/running/topic-hierarchy.rst, wis2box-management/Dockerfile, wis2box-management/MANIFEST.in, wis2box-management/docker/entrypoint.sh, wis2box-management/wis2box/topic_hierarchy.py
=> add pywcmp topic hierarchy validation (#228)

docker-compose.wis2box-ftp.yml, docs/source/user/data-ingest.rst, docs/source/user/public-services-setup.rst
wis2box-ftp as added service for data-ingestion
=> wis2box-ftp as added service for data-ingestion

wis2box-management/docker/entrypoint.sh, wis2box-management/docker/wis2box.cron
=> run station publishing on startup and every 10 minutes (#410)

docker-compose.wis2box-ftp.yml, docs/source/user/data-ingest.rst
wis2box FTP fixes
- pasv fixes , override same ports as used in config
- add env-variables so user can set pasv_address to match host running ftp
=> Wis2box ftp fix

docker-compose.yml, docs/requirements.txt, docs/source/reference/quickstart.rst, docs/source/reference/running/data-pipeline-plugins.rst, docs/source/user/setup.rst, tests/integration/test_workflow.py, wis2box-management/Dockerfile, wis2box-management/docker/entrypoint.sh, wis2box-management/wis2box/data/csv2bufr.py, wis2box-management/wis2box/data/synop2bufr.py
- always restart docker services
- unpin nbsphinx (upstream issue fixed)
- update plugin docs
- use explicit version in user docs for downloading release (for easy copy/paste) (n.b.: this has been added as a deployment step for future releases)
- unpin BUFR tools while in development
- force remove pywcmp JSON bundle of topic hierarchy on wis2box-management docker entrypoint
=> various updates

docs/source/index.rst, docs/source/reference/running/data-pipeline-plugins.rst, wis2box-management/wis2box/data/synop2bufr.py
=> safeguard synop2bufr testing, add notes on year/month requirements to documentation

wis2box-management/Dockerfile, wis2box-management/wis2box/data/__init__.py, wis2box-management/wis2box/metadata/discovery.py
This PR does a match/check of topic hierarchy between discovery metadata and data mappings at the time of design time workflow. Addresses #431.
=> check for topic hierarchy on dataset publishing (#431)

examples/config/synop-bin-mappings.yml, examples/config/synop-bufr-mappings.yml, examples/config/synop-csv-mappings.yml
ensure valid regex in examples
=> fix file pattern examples

tests/integration/test_workflow.py, wis2box-management/wis2box/metadata/discovery.py, wis2box-management/wis2box/storage/minio.py
=> fix message publication for discovery metadata (#454)

wis2box-management/Dockerfile
=> Update to versions of csv2bufr, synop2bufr and pymetdecoder used.

wis2box-management/wis2box/cli_helpers.py, wis2box-management/wis2box/metadata/station.py
Emit geometry z value if a meaningful value is found in `station_list.csv`.
=> safeguard station metadata geometry z

docker-compose.yml, docs/source/user/getting-started.rst, docs/source/user/setup.rst
health-check plus minor fix in docs (I really do recommend Ubuntu 20.04 LTS instead of 22.04 LTS ...)
=> Maaike updates

wis2box-management/wis2box/metadata/station.py
=> test station coordinate types (#477)

.github/workflows/tests-docker.yml, docs/source/reference/monitoring/index.rst, prometheus/prometheus.yml, wis2box-broker/Dockerfile, wis2box-broker/entrypoint.sh
=> add sensible default for monitoring retention

docker-compose.monitoring.yml, docs/source/reference/monitoring/index.rst, prometheus/prometheus.yml
Fixes Prometheus [startup issue in CI](https://github.com/wmo-im/wis2box/actions/runs/5945844137/job/16125534961#step:9:61).
=> move Prometheus retention to startup

wis2box-management/wis2box/metadata/station.py
Refreshes stations collection by station (#498).
=> refresh station metadata by station (#498)

docs/source/reference/auth.rst, wis2box-management/docker/entrypoint.sh, wis2box-management/wis2box/auth.py
wis2box-auth updates to add default restrictions on wis2box processes and collections/stations.
=> Add default restrictions on wis2box processes and collections/stations

.github/workflows/tests-docker.yml, wis2box-management/wis2box/data/bufr4.py
Fix for #533. Headers now copied from source file to the output file.
=> Bug fix, BUFR to BUFR

wis2box-create-config.py
to fix https://github.com/wmo-im/wis2box/issues/540
=> fix global bounding box

docs/source/user/getting-started.rst
Increase storage requirement in docs to avoid disk space isssues when moving to a new release
=> increase storage requirement

docs/source/community/troubleshooting.rst, docs/source/user/setup.rst
we found some typo's when running through docs with Dwayne
=> update  typos

wis2box-create-config.py
to fix https://github.com/wmo-im/wis2box/issues/553
=> fix issue 553

wis2box-management/wis2box/metadata/station.py
=> do not calculate barometer_height (#511)

wis2box-management/wis2box/data/bufr4.py
fix for https://github.com/wmo-im/wis2box/issues/559
=> fix for issue-559

docs/source/user/public-services-setup.rst
Hi Tom, I got a lot of questions on how to use SSL certificates in wis2box recently. I'm doing this  PR to  help improve the documentation on this.
=> updated docs for SSL

wis2box-management/Dockerfile
=> fix Shapely requirement

wis2box-management/wis2box/metadata/station.py
https://github.com/wmo-im/wis2box/issues/581
=> fix for issue-581

tests/integration/test_workflow.py, wis2box-management/wis2box/metadata/station.py
Issue-581 was not properly fixed, here is the additional fix required
I also noted that the argument 'wsi' in load_stations-function was unused so I removed it.
=> Issue 581 fix2

docs/source/_templates/about.html
=> fix logo, link to new website

docker-compose.yml
=> wis2box-api:1.0b6

docs/source/reference/configuration.rst, tests/test.env, wis2box-create-config.py
Requires https://github.com/wmo-im/wis2box-ui/pull/80/
=> Create environment variable for default language

wis2box-management/docker/wis2box.cron, wis2box-management/wis2box/metadata/discovery.py
New CLI command "wis2box metadata discovery republish" to address https://github.com/wmo-im/wis2box/issues/661 and in support of https://github.com/wmo-im/wis2box/issues/655
=> metadata republish

nginx/nginx-ssl.conf
add x_api_http_method to /auth to avoid unauthorized updates to stations and metadata
=> add x_api_http_method to /auth

wis2box-create-config.py
=> default log-level should be WARNING not ERROR

wis2box-management/docker/entrypoint.sh, wis2box-management/wis2box/api/config/pygeoapi.py
The discovery-metadata should not be an editable collection, only stations are updated via API-calls by wis2box-webapp
=> only stations should be editable collection

wis2box-ctl.py
=> update docstring (#698)

.github/workflows/tests-docker.yml, docs/source/reference/quickstart.rst, docs/source/user/data-ingest.rst, tests/data/metadata/discovery/cd-surface-weather-observations.yml, tests/integration/test_workflow.py, wis2box-management/wis2box/auth.py, wis2box-management/wis2box/metadata/discovery.py, wis2box-management/wis2box/pubsub/message.py
=> add security property to WNM for access controlled data (#643)

wis2box-ctl.py
=> suppress daemon errors (#747)

wis2box-management/wis2box/pubsub/subscribe.py
https://github.com/wmo-im/wis2box/issues/761
=> do not process archived data

wis2box-mqtt-metrics-collector/mqtt_metrics_collector.py
fix for https://github.com/wmo-im/wis2box/issues/781
Note that this issue impacts daycli and I'd like to release the fix along with the other PRs related to fix daycli-issues
=> Issue 781 monitoring

docs/source/user/data-ingest.rst
=> fix doc typo (#780)

wis2box-management/wis2box/data_mappings.py
https://github.com/wmo-im/wis2box/issues/754
=> protect against empty data-mappings

docker-compose.yml
pin wis2downloader to use v0.3.2
=> pin wis2downloader to use v0.3.2

docker-compose.data-subscriber.yml
add comment
set default log-level to INFO
remove COUNTRY_ID as it is no longer required ...
=> update data-subscriber config for campbell MQTT

docker-compose.yml, docs/source/user/public-services-setup.rst
https://github.com/wmo-im/wis2box/issues/752
the mosquitto-volume introduced in a previous PR plus some docs to indicate how to add new users should be sufficient to satisfy the requirement for issue-752
=> docs for adding users

.github/workflows/trivy.yml
=> add scheduler to trivy action (#836)

wis2box-management/Dockerfile
(Note: associated PR in https://github.com/wmo-im/wis2box-api/pull/89).
=> update pyoscar to 0.9.0

grafana/dashboards/home.json, wis2box-mqtt-metrics-collector/mqtt_metrics_collector.py
Fix for https://github.com/wmo-im/wis2box/issues/884
=> Issue 884: force metrics-collector to wait for wis2box-api and avoid buffer_lock

wis2box-management/wis2box/data/bufr2geojson.py, wis2box-management/wis2box/data/bufr4.py, wis2box-management/wis2box/data/csv2bufr.py, wis2box-management/wis2box/data/synop2bufr.py, wis2box-management/wis2box/data/universal.py
https://github.com/World-Meteorological-Organization/wis2box/issues/890
Screenshot demonstrating logging  while purposefully messing-up data-mappings, using the code in this PR:
=> Issue 890 filepattern improved errors

wis2box-management/wis2box/metadata/discovery.py
https://github.com/World-Meteorological-Organization/wis2box/issues/908
=> prevent duplicate links

tests/integration/test_workflow.py, wis2box-management/wis2box/metadata/discovery.py
Addresses https://github.com/wmo-im/wcmp2/issues/245
=> suppress wmo:topicHierarchy in WCMP2 publication

wis2box-management/wis2box/data/cap_message.py
https://github.com/World-Meteorological-Organization/wis2box/issues/789
=> handle filename with multiple dots

tests/data/metadata/station/wmo-test-drifting-buoys.csv, tests/data/metadata/station/wmo-test-ship.csv, wis2box-management/wis2box/metadata/station.py
Fixes in wis2box-management for
https://github.com/World-Meteorological-Organization/wis2box/issues/848
Separate PR required to add support in wis2box-webapp
=> Support non fixed stations

docs/source/user/downloading-data.rst
To address issue raised by @gespau https://github.com/World-Meteorological-Organization/wis2box/issues/941
=> wis2downloader docs update

docs/source/reference/configuration.rst, wis2box.env.example
=> add custom contact/identification env vars (#341)

tests/data/metadata/discovery/cd-surface-weather-observations.yml, wis2box-management/wis2box/metadata/discovery.py
=> metadata: hotfix time.resolution (#966)
