World-Meteorological-Organization/wis2box

- wis2node/metadata/discovery.py
This PR adds a canonical link to wis2node discovery metadata.  This will help in keeping clear the authoritative source as per WIS 2.0 architecture.
> add canonical link to discovery metadata

- docker/data-consumer/config/subscribe/gisc-ca.conf
- docker/data-consumer/config/subscribe/gisc-de.conf.off
The canadian feed was pulling in nwp model extracts from american regional model, as well as some local pictorial products.  It caused the feed to lag, also using only one process was not fast enough (serial downloads to slow) increased to 5.
A german feed is provided, but people need to request their own accounts. Description in the gisc-de.conf.off file itself.
> improved Canadian "GISC" feed, initial dwd feed disabled.

- requirements.txt
- wis2node/api/backend/elastic.py
- wis2node/api/config/pygeoapi.py
This PR updates the API backend to support daily indexes for datasets.  The idea here is to create indexes based on their YYYY-MM-DD:
- `observations-surface-land.mw.fwcl.landfixed.2021-07-07`
- `observations-surface-land.mw.fwcl.landfixed.2021-07-08`
- ...
ES Index access from pygeoapi then becomes `http://localhost:9200/observations-surface-land.mw.fwcl.landfixed.*/_search`.
The benefit is also being able to delete entire daily indexes based on date (retention) easily and efficiently.
Metadata (discovery, station) indexes are unaffected.
This also puts a hard link to the incoming dataset's GeoJSON file to have a `properties.phenomenonTime` as per the OM GeoJSON (cc @david-i-berry).  So part of any wis2node plugin setup will require that GeoJSON emitted has this property (need …
> API: support daily indexes for datasets

- .github/ISSUE_TEMPLATE/user-story.md
- .github/workflows/docs.yml
- .github/workflows/tests-docker.yml
- CONTRIBUTING.md
- SECURITY.md
- docker/data-consumer/config/subscribe/gisc-ca.conf
- docker/data-consumer/config/subscribe/gisc-de.conf.off
- docker/docker-compose.webdav.yml
- docker/docker-compose.yml
- docker/pygeoapi/wait-for-elasticsearch.sh
- docs/source/administration.rst
- docs/source/conf.py
- docs/source/configuration.rst
- docs/source/extending-wis2box.rst
- docs/source/how-wis2box-works.rst
- docs/source/installation.rst
- docs/source/quickstart.rst
- docs/source/running/api-publishing.rst
- docs/source/running/data-ingest-processing-and-publishing.rst
- setup.py
- tests/data/metadata/discovery/surface-weather-observations.yml
- wis2box-ctl.py
- wis2box/data/__init__.py
- wis2box/resources/data-mappings.yml
- wis2box/topic_hierarchy.py
This PR adds a number of minor fixes:
- trailing spaces ijn files
- documentation
- adds top level WMO topic hierarchy to example paths (i.e. `data.core`)
- only publish live documentation on changes to `main` branch
> WMO topic hierarchy and minor fixes

- docker/data-consumer/config/watch/incoming.conf
- docker/wis2box/config/subscribe/data-api-publish.conf
- docker/wis2box/config/subscribe/data-ingest.conf
sr3 log setting to omit those messages (corresponding to every time a source is polled.)
the new log setting is to log when a message is received, and then when the action on the message is performed.
> remove "gather" log messages from data-consumer and wis2box containers.

- docker/data-consumer/config/watch/incoming.conf
With this setting change... no matter how old a file is when copied into the incoming directory,
it will be accepted and posted.
> for testing and development, it is just annoying to have old files ignored

- docker/ca-republisher/config/default.conf
- docker/ca-republisher/config/subscribe/ca-republisher.conf
- docker/data-consumer/config/default.conf
- docker/data-consumer/config/watch/incoming.conf
- docker/de-republisher/config/default.conf
- docker/default.env
- docker/mqp-publisher/config/default.conf
- docker/mqp-publisher/config/subscribe/public.conf
- docker/wis2box/config/default.conf
- docker/wis2box/config/subscribe/data-api-publish.conf
- docker/wis2box/config/subscribe/data-ingest.conf
The date directory is now in the baseURL as specified by TT-Protocols group.
Confirmed that part was correct for both republishing from CA- fake gisc, and 
local products for Malawi.
next step is to produce data-access jupyter examples.
> Mqp cfg tweaks... did some mqp message inspection for ca and mw products

- .github/workflows/tests-docker.yml
- wis2box/api/__init__.py
- wis2box/api/backend/elastic.py
Observation collections published to the OAPI with the ElasticSearch backend require defining the field: `phenomenonTime` in the geoJSON properties block. This is required to sort observations by date with the API.  The required field: `phenomenonTime` refers to the time of the observation. The optional field: `resultTime` refers to the time the observation was published.
> Add phenomenonTime requirement

- .gitattributes
Was working with @chenxiaoxia2019 on issues with Mosquito and pygeoapi containers getting the error:
```
standard_init_linux.go:228: exec user process caused: no such file or directory
```
The solution is add a behavior in `.gitattributes` for end of line characters of `.sh`/shell scripts to use the line feed (LF) character.
> Use line feed end of line character in shell scripts

- docker/default.env
- docker/docker-compose.yml
- docs/source/configuration.rst
- docs/source/quickstart.rst
- Pass URLs defined in `default.env` and `dev.env` to wis2box-ui.
- Add some clarification to docs that URLs defined in `default.env` need to be defined in `dev.env` when using remote host.
> Pass wis2box urls to wis2box-ui

- wis2box/env.py
- wis2box/metadata/discovery.py
- Add `items/` to fix oafeat link
- Use public MQTT URL instead of URL derived from broker in docker system.
> Use correct links in discovery metadata

- .github/workflows/ghcr.yml
- .github/workflows/tests-docker.yml
- Dockerfile
- docker/auth/Dockerfile
- docker/docker-compose.monitoring.yml
- docker/docker-compose.override.yml
- docker/docker-compose.yml
- docker/docker-compose.yml.promtail
- docs/source/installation.rst
- docs/source/monitoring/index.rst
- wis2box-ctl.py
- wis2box/data/observations.py
- Update workflow for  publication to ghcr.io. Use `docker/metadata-action` to create tags. Publish on release as well as commits to main.
- Update test workflow. Build and pull all containers during the build step instead of pulling on start. Cache stations before publishing discovery metadata.
- Use ghcr version of wis2box for wis2box-auth.
- wis2box depends on wis2box-api container.
> Small fixes

- .github/workflows/tests-docker.yml
- docs/source/quickstart.rst
- wis2box/metadata/station.py
- Update test workflow to run against both CLI and pure event workflow.
- Update quickstart documentation.
- Throw more graceful warnings when publishing stations with incomplete collections.
> Throw more graceful errors during quickstart

- .github/workflows/tests-docker.yml
- wis2box-ctl.py
- wis2box/api/__init__.py
- wis2box/cli_helpers.py
- wis2box/data/__init__.py
- Add execute command to wis2box-ctl to run shell-like commands in the wis2box container without logging in to the container.
- Move recursive CLI option to cli_helpers.py
> Add `wis2box-ctl.py execute` command 

- wis2box/metadata/station.py
I noted that caching my stations was working incorrectly when my list contained multiple tsi with empty strings. This is a hot-fix to address this issue.
> fix station cache for empty tsi

- wis2box/data/bufr4.py
bufr2geojson derives the file name from the `typical[TIME]` fields. This PR sets the time in the header the same of the time of the observation of the each subset.
> Correct time in bufr header

- Dockerfile
- docker/docker-compose.yml
- docker/wis2box/wis2box.cron
a fix for https://github.com/wmo-im/wis2box/issues/240
I added a third cronjob that prints a mesage to indicate the cron-service is alive
stdout and stderr logs for cronjobs are redirected to /proc/1/fd/1-2  to ensure they end up in the docker logs
> fix wis2box cron

- Dockerfile
- wis2box-ctl.py
Docker file updated to add Debian bookworm to source list and to then install the latest version of the ecCodes BUFR tables from bookworm. The tables are not available as part of bullseye.
> Bufr tables latest

- wis2box/data/base.py
- wis2box/plugin.py
- wis2box/pubsub/mqtt.py
- wis2box/pubsub/subscribe.py
Adds a `client_type` qualifier to pubsub broker to more clearly identify scope/workflow of a given pubsub client.
> add client id to pubsub broker client

- docker/docker-compose.yml
restart: always,  in combination with memory-limits so container restarts after stop due to memory-limit hit and the stack will remain alive despite memory-leaks
> add restart always and mem-limits

- docker/docker-compose.monitoring.yml
- wis2box/pubsub/subscribe.py
- Run Handle as a multiprocess to reduce memory leaks
- Mount the docker.sock explicity
- Use a tag of cadvisor that supports both arm64 and am64
> Performance enhancements

- wis2box/data/bufr4.py
- wis2box/pubsub/mqtt.py
- wis2box/pubsub/subscribe.py
- [wis2box/data/bufr4.py](https://github.com/wmo-im/wis2box/pull/309/files#diff-6835ec72c1a17fa84743214ed0ae5e9316f9044c629a4650452c54a87c2b459e) => always logs “Failed to publish: None” because it only ever is called if wsi is None
- [wis2box/pubsub/mqtt.py](https://github.com/wmo-im/wis2box/pull/309/files#diff-2aa2e66331d485ca5d41e4f84748fbc5d360f0469bb03cbf2887175541faab93) => Added f-strings to actually make the variables interpolate
- [wis2box/pubsub/subscribe.py](https://github.com/wmo-im/wis2box/pull/309/files#diff-e2baaf6ed87f876b1adcc40681a4861e417dd47ead5c1da1ecdbe2ef33ee3413) => Remove unnecessary double quotes
> Syntax fixes

- docker/grafana/dashboards/home.json
- docker/mqtt_metrics_collector/mqtt_metrics_collector.py
- wis2box/data/base.py
- wis2box/handler.py
I noted that testing with a bufr with multiple messages, in which some stations were ok but other were reporting did not work for my monitoring so I added these fixes. 
Initiate local_broker when publishing message
More granular timing in grafana dashboard
> monitoring fix

- grafana/dashboards/home.json
PR 362 renamed the wis2box-container to wis2box-management, update the dashboard to grep errors using the new container name
> fix to display errors wis2box-management container

- docker-compose.yml
The minio-interface keeps changing recently due to wis2box pulling in the latest version of minio, which makes the documentation screenshots inconsistent (and I dislike the new login-window with ads for commercial versions...)
I would recommend we fix minio to this release.
> pin minio release image: 2022-12-02T19-19-22Z.fips

- .github/workflows/tests-docker.yml
- tests/integration/test_workflow.py
- wis2box-management/wis2box/data/base.py
- wis2box-management/wis2box/pubsub/message.py
Addresses #391 
- updates `id` from string to UUID (WNM [requirement](https://wmo-im.github.io/wis2-notification-message/standard/wis2-notification-message-DRAFT.html#_identifier)).  This change results in an additional 15 messages being generated as part of the integration tests (thanks @webb-ben for catching)
- adds `properties.datetime`, which is currently [required](https://wmo-im.github.io/wis2-notification-message/standard/wis2-notification-message-DRAFT.html#_temporal_description_datetime_start_datetime_end_datetime) in WNM (note: this is currently in [discussion](https://github.com/wmo-im/wis2-notification-message/issues/34) in TT-WISMD to make optional, but it makes sense for wis2box to provide given message generation is close to the data pipeline, and can be easily derived)
- …
> update WNM generation (#391)

- docs/source/reference/administration.rst
- docs/source/reference/auth.rst
- docs/source/reference/configuration.rst
- docs/source/reference/data-access/python-api-owslib.ipynb
- docs/source/reference/data-access/python-api-requests.ipynb
- docs/source/reference/data-access/qgis-api.rst
- docs/source/reference/data-access/r-api.ipynb
- docs/source/reference/quickstart.rst
- docs/source/reference/services.rst
- docs/source/user/public-services-setup.rst
- docs/source/user/setup.rst
- tests/integration/test_workflow.py
this fixes the inconsistency when installing from the archive, though 8999 is still referenced multiple times in the reference guide.
> install from archive uses port 80

- docs/source/reference/running/data-mappings.rst
- tests/integration/test_workflow.py
- wis2box-management/Dockerfile
- wis2box-management/wis2box/data/csv2bufr.py
> allow plugin templates to be local or external (#405)

- tests/integration/test_workflow.py
- wis2box-management/Dockerfile
- wis2box-management/wis2box/data/bufr4.py
Depends on https://github.com/wmo-im/bufr2geojson/pull/21
> force error handling in bufr2geojson (#415)

- docs/requirements.txt
- docs/source/user/data-ingest.rst
This PR pins nbsphinx to `<0.9` given a possible issue in https://github.com/spatialaudio/nbsphinx/issues/720, which breaks building on RTD.
> pin nbsphinx for RTD build

- .github/workflows/tests-docker.yml
- default.env
- docker-compose.yml
- docs/source/reference/data-access/r-api.ipynb
- docs/source/reference/quickstart.rst
- docs/source/reference/running/api-publishing.rst
- nginx/nginx-ssl.conf
- nginx/nginx.conf
- wis2box-management/docker/entrypoint.sh
- wis2box-management/docker/wis2box.cron
- wis2box-management/requirements.txt
- wis2box-management/wis2box/api/backend/elastic.py
- wis2box-management/wis2box/api/config/pygeoapi.py
- wis2box-management/wis2box/metadata/discovery.py
In support of #154 
- updates to ES8
- updates based on latest pygeoapi (https://github.com/wmo-im/wis2box-api/pull/25)
- adds editable endpoints for metadata resources (metadata UI)
- POST/PUT/DELETE commands on `/oapi/collections/discovery-metadata` and `/oapi/collections/stations` will need admin auth
❗❗❗  Note: this is a breaking change❗❗❗
Users will need to clear their ES data with:
```bash
docker volume rm wis2box_project_es-data
docker volume rm wis2box_project_api-config
```
...before installing the forthcoming 1.0.b2 release.
As an alternative workaround, from the elasticsearch container:
```bash
curl -XDELETE http://localhost:9200/discovery-metadata
curl -XDELETE http://localhost:9200/stations
```
...however we would have to verify that the observations are intact with the ES …
> update to Elasticsearch 8 and latest pygeoapi, add wis2box-ui-admin

- wis2box-management/wis2box/api/backend/elastic.py
- wis2box-management/wis2box/data/__init__.py
- skips `/metadata` based objects for data cleaning
- qualifies ES function with named parameter
- `s/object/obj/g` (`object` is a Python keyword)
> skip metadata on data cleaning

- wis2box-management/Dockerfile
Installs the wis2box package (in the wis2box-management container) as an editable package, which is useful for in-container debugging as required.
> avoid installing wis2box as a Python egg

- tests/integration/test_workflow.py
- wis2box-management/wis2box/pubsub/message.py
> ensure notification message integrity is encoded as base64

- .github/workflows/tests-docker.yml
- docs/source/community/troubleshooting.rst
- docs/source/user/data-ingest.rst
- docs/source/user/downloading-data.rst
- docs/source/user/getting-started.rst
- wis2box-ctl.py
Addresses #471.  `wis2box-ctl.py` also has a check for `docker-compose` or `docker compose`, although we may consider locking on only `docker compose`.
@maaikelimper would we still require https://docs.wis2box.wis.wmo.int/en/latest/community/troubleshooting.html given the V2 requirement?
> require docker compose v2 support (#471)

- .github/workflows/tests-docker.yml
- docker-compose.dev.yml
- docs/source/reference/running/api-publishing.rst
- wis2box-management/wis2box/api/__init__.py
- wis2box-management/wis2box/api/config/base.py
- wis2box-management/wis2box/api/config/pygeoapi.py
- wis2box-management/wis2box/data/__init__.py
Fixes `wis2box data delete-collection` workflow, updates docker-dev setup.
> fix delete dataset workflow

- docs/source/reference/running/station-metadata.rst
- docs/source/user/setup.rst
- wis2box-management/Dockerfile
- wis2box-management/wis2box/metadata/station.py
> add tool to query OSCAR to support station management (#469)

- docker-compose.dev.yml
- nginx/nginx.conf
- wis2box-ctl.py
Sets custom header on `/oapi` endpoint to help wis2box-auth detect whether a given request is an API Transaction.
Related: https://github.com/wmo-im/wis2box-auth/pull/5
> add custom header for wis2box-auth detection of API transactions

- .github/workflows/tests-docker.yml
- config-templates/metadata-synop.yml.tmpl
- config-templates/metadata-temp.yml.tmpl
- examples/config/surface-weather-observations.yml
- tests/data/metadata/discovery/cog-surface-weather-observations.yml
- tests/data/metadata/discovery/dza-surface-weather-observations.yml
- tests/data/metadata/discovery/ita-surface-weather-observations.yml
- tests/data/metadata/discovery/mwi-surface-weather-observations.yml
- tests/data/metadata/discovery/rou-synoptic-weather-observations.yml
- wis2box-management/Dockerfile
- wis2box-management/requirements.txt
- wis2box-management/wis2box/api/backend/elastic.py
- wis2box-management/wis2box/metadata/discovery.py
This PR provides updates for WCMP2 support against the latest draft.
- users will need to republish their discovery metadata as a result of the change/update
> pygeometa and WCMP2 updates

- tests/integration/test_workflow.py
- wis2box-management/wis2box/data/base.py
- wis2box-management/wis2box/metadata/discovery.py
- wis2box-management/wis2box/pubsub/message.py
- wis2box-management/wis2box/storage/__init__.py
- wis2box-management/wis2box/storage/base.py
- wis2box-management/wis2box/storage/minio.py
- wis2box-management/wis2box/storage/s3.py
- update notification message for discovery metadata
- ensure canonical link points to WCMP2 document (not MCF)
- ensure media type is `application/geo+json`
- ensure notification messages do not include any part of `origin/a/wis2`
- update discovery metadata
- ensure contact postalcode is always a string
- ensure temporal begin date is set, if not set by user before publishing
- set media type in storage
> discovery metadata/notification message updates

- docs/source/reference/quickstart.rst
- tests/integration/test_workflow.py
- wis2box-management/wis2box/pubsub/message.py
In WNM, include data/metadata inline as per the specification (suggested at W2AT 2023-11-13).
> provide data inline to WNM

- wis2box-management/wis2box/metadata/station.py
While working with Brazil I noted that they used secondary primary IDs from their stations in OSCAR. In order to create a working station-list for their data the secondary wsi needs to be inserted in their station-metadata, requiring this minor fix.
> use input wsi instead of returned value

- config-templates/metadata-synop.yml.tmpl
- config-templates/metadata-temp.yml.tmpl
- docs/source/user/setup.rst
- examples/config/surface-weather-observations.yml
- tests/data/metadata/discovery/cog-surface-weather-observations.yml
- tests/data/metadata/discovery/dza-surface-weather-observations.yml
- tests/data/metadata/discovery/ita-surface-weather-observations.yml
- tests/data/metadata/discovery/mwi-surface-weather-observations.yml
- tests/data/metadata/discovery/rou-synoptic-weather-observations.yml
- wis2box-management/Dockerfile
- wis2box-management/docker/entrypoint.sh
- wis2box-management/requirements.txt
- wis2box-management/wis2box/topic_hierarchy.py
Fixes #532.  In addition, updates WCMP2 MCFs to the latest WTH lookups.  Finally, use [pywis-topics](https://github.com/wmo-im/pywis-topics) (which was pulled out of pywcmp) for WTH handling (note that WTH handling continues to be commented out until WTH is officially approved).
> updates WCMP2 docs, examples and pywis-topics

- wis2box-management/wis2box/data/bufr4.py
- add temp_wsi to error to help indicate which subset caused the error
- print error when location is missing in subset
> more explicit error logging in bufr-to-bufr

- docs/source/community/troubleshooting.rst
- docs/source/user/setup.rst
- wis2box-management/wis2box/api/__init__.py
- wis2box-management/wis2box/api/backend/base.py
- wis2box-management/wis2box/api/backend/elastic.py
- wis2box-management/wis2box/data/__init__.py
- wis2box-management/wis2box/metadata/station.py
Updates to assist migration to new topic-hierarchy and to assist users in associating station with a topic
- new option to 'add-topic' to stations in station-metadata
- new option to copy data between collections by reindexing
> Update station topic

- docs/source/reference/configuration.rst
- docs/source/user/data-ingest.rst
- tests/test.env
- wis2box-create-config.py
cc: https://github.com/wmo-im/wis2box/issues/588
TODO:Documentation
> Create env variable for UI Cluster

- wis2box-ctl.py
> /dev/null does not work when splitting the argument, just remove it otherwise we have the message:
Error response from daemon: setting ">" not found in the plugin configuration
when starting the wis2box for the first time ...
> remove > /dev/null 2&1

- wis2box-management/requirements.txt
- wis2box-mqtt-metrics-collector/requirements.txt
paho-mqtt 2 is now at RC2.  This PR pins to using 1.x.  We revisit the migration/upgrade once paho-mqtt 2 stable is released and tried/tested further.
> safeguard paho-mqtt to <2

- nginx/nginx-ssl.conf
- nginx/nginx.conf
nginx has not been compressing `application/javascript` due to a typo in the header. Fixing this compresses wis2box-ui from 1.9mb to 726kb.
> Fix typo in nginx gzip types

- wis2box-management/Dockerfile
- wis2box-management/wmdr-codelists/FacilityType.csv
- wis2box-management/wmdr-codelists/InstrumentOperatingStatus.csv
- wis2box-management/wmdr-codelists/TerritoryName.csv
- wis2box-management/wmdr-codelists/WMORegion.csv
Fix/workaround for https://github.com/wmo-im/wis2box/issues/658
> fix for issue 658

- docker-compose.monitoring.yml
From the documentation
I updated the logging option for loki to add this options to reduce unnecessary disk-space usage by logs
> avoid unnecessary disk-space used by logs

- wis2box-management/Dockerfile
- wis2box-management/wmdr-codelists/FacilityType.csv
- wis2box-management/wmdr-codelists/InstrumentOperatingStatus.csv
- wis2box-management/wmdr-codelists/TerritoryName.csv
- wis2box-management/wmdr-codelists/WMORegion.csv
Fixes #658 (again, given there is a regression on codes.wmo.int).
This reverts commit 7b4ed20ba9447b6be25e52e11f60dd0bc4e5b4d2.
> Revert "Revert "fix for issue 658 (#659)""

- .github/workflows/zaproxy.yml
- .zap/rules.tsv
To address https://github.com/wmo-im/wis2box/issues/654
> reinit zaproxy PR

- docker-compose.yml
Pin MinIO to latest cpuv1 release, to avoid the error: Fatal glibc error: CPU does not support x86-64-v2
See:
https://github.com/minio/minio/issues/18365
> MinIO version to support older CPUs

- docker-compose.dev.yml
- docker-compose.monitoring.yml
- docker-compose.yml
- grafana/dashboards/elasticsearchhealthmonitoring.json
- grafana/dashboards/home.json
- grafana/dashboards/wis2downloader.json
- prometheus/prometheus.yml
Fix issue 674:
Add new dashboard to monitor the health of elasticsearch:
Alert List Panel:
This panel provides an overview of current alerts, specifically those in the "alerting" state, with a maximum of 10 alerts displayed.
Elasticsearch Disk Space Utilization Panel:
Monitors the percentage of disk space used in the Elasticsearch cluster (es-wis2box).
Alerts trigger if disk usage exceeds 90%, with thresholds visually represented by color codes (green, yellow, dark red).
Elasticsearch Available Disk Space Panel:
Displays the total amount of free disk space across all nodes in the cluster.
Alerts trigger if available disk space drops below 10 GB, with similar color-coded thresholds.
Alerting Configuration:
High Storage Usage Alert:
Triggers when disk space usage exceeds 90% for more than 5 …
> Issue 674 new

- docker-compose.monitoring.yml
- loki/loki-config.yml
I have noted that the disk usage over time is related due to the loki log retention not kicking in and excessive logging  (info vs warning) by grafana/prometheus/loki containers. I started this PR to apply some fixes to reduce the burden of the monitoring-stack on the host-system !
> improved monitoring stack

- wis2box-management/wis2box/data/bufr4.py
- wis2box-management/wis2box/data/csv2bufr.py
- wis2box-management/wis2box/data/synop2bufr.py
to support the datacentric approach, the api-functions now require to receive a metadata_id
> metadata for data-centric api

- .github/workflows/containers.yml
wis2downloader removed from list of images to build, now built and published externally. This should fix the related error in the publish image workflow.
> wis2downloader removed from image build workflow

- wis2box-mqtt-metrics-collector/mqtt_metrics_collector.py
When monitoring the increase of a metric using prometheus-query, the first entry for a label is not detected since increase() can only detect the difference between 2-scrapes. This is a minor issue that only affects the first time a label is created but it is a bit confusing for training when we always start with a brand new instance.
This PR fixes this by waiting 5 seconds (scrape interval) for a new label-entry in a metric.
> to deal with first label in metric

- .github/workflows/tests-docker.yml
- tests/data/CAP/cap_example.xml
- tests/data/metadata/discovery/cd-surface-weather-observations.yml
- tests/data/metadata/discovery/int-wmo-test-cap.yml
- tests/data/metadata/discovery/int-wmo-test-drifting-buoys.yml
- tests/data/metadata/discovery/int-wmo-test-ship-hourly.yml
- tests/data/metadata/discovery/int-wmo-test-wind-profile.yml
- tests/integration/test_workflow.py
- tests/send_CAP_as_message.py
https://github.com/wmo-im/wis2box/issues/766
> add CAP test

- tests/integration/test_workflow.py
- wis2box-management/wis2box/pubsub/message.py
- update GRIB/BUFR media types given they are now approved by IANA
- update `generated_by` for consistency with other tools such as pywcmp
> update GRIB/BUFR media types

- docs/source/user/getting-started.rst
https://github.com/wmo-im/wis2box/issues/793
> update for Ubuntu 24.0.4 as per feedback from WIS2 Training Brasilia channel

- wis2box-management/wis2box/metadata/station.py
https://github.com/wmo-im/wis2box/issues/802
> don't add topics to links, don't remove topics

- wis2box-management/wis2box/api/config/pygeoapi.py
- wis2box-management/wis2box/metadata/discovery.py
- wis2box-management/wis2box/pubsub/message.py
Upon digging through the code I find various cases where we can prevent 404 on the wis2box-api by changing the methods checking for items stored via the API which I fixed in this PR
While doing this I found one issue in `publish_discovery_metadata` which might be the cause for :
https://github.com/wmo-im/wis2box/issues/807
> reduce preventable 404 on the wis2box-api

- docker-compose.yml
improved settings for elasticsearch and minio, related to https://github.com/wmo-im/wis2box/issues/814
> container config updates

- .zap/rules.tsv
- docker-compose.yml
- tests/integration/test_workflow.py
- wis2box-management/wis2box/api/__init__.py
- wis2box-management/wis2box/api/backend/elastic.py
- wis2box-management/wis2box/data/__init__.py
- wis2box-management/wis2box/data/bufr2geojson.py
- wis2box-management/wis2box/data/geojson.py
- wis2box-management/wis2box/data_mappings.py
- wis2box-management/wis2box/metadata/discovery.py
https://github.com/wmo-im/wis2box/issues/806
>  reorganizing the data-collection for new bufr2geojson oaproc output

- tests/integration/test_workflow.py
- wis2box-management/wis2box/auth.py
> remove security handling in WCMP2 links

- docs/source/reference/configuration.rst
- wis2box-create-config.py
Includes additional environment variables to the docs as implemented in https://github.com/wmo-im/wis2box-ui/pull/95
Addresses:
https://github.com/wmo-im/wis2box-ui/issues/93
https://github.com/wmo-im/wis2box-ui/issues/98
> Include additional UI variables in docs

- wis2box-management/Dockerfile
- wis2box-management/docker/entrypoint.sh
- wis2box-management/requirements.txt
> remove pywis-topics (unused) (#813)

- docs/source/reference/running/data-pipeline-plugins.rst
- wis2box-management/wis2box/data/cap_message.py
- wis2box-management/wis2box/util.py
set CAP signature check based on env variable
https://github.com/wmo-im/wis2box/issues/823
> set CAP signature check based on env variable

- .github/workflows/zaproxy.yml
- wis2box-management/wis2box/auth.py
> safeguard auth paths

- wis2box-management/wis2box/metadata/discovery.py
https://github.com/World-Meteorological-Organization/wis2box/issues/929
I believe this is issue is caused because we only setup the config for the geojson-collection during the container startup, this change also runs setup_collection from wis2box.api  when the dataset is created/updated
> add config for geojson-collection when dataset is published with 2geojson data-plugin
